// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Миграции и seed ходят по ПРЯМОМУ соединению, а рантайм приложения — по
    // пулу (см. lib/prisma.ts). На хостингах с pgbouncer/пулером (Neon,
    // Supabase) DATABASE_URL указывает на пул в transaction-режиме, где
    // `prisma migrate deploy` работать не может: ему нужны сессионные
    // advisory-локи и DDL в одной сессии. Поэтому здесь предпочитаем
    // DIRECT_URL, а на локальной машине его просто нет и берётся DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
